export const WORDS = [
  { word: 'Apfel', art: 'der', meaning: 'apple', plural: 'Äpfel', pType: 'none' }, { word: 'Banane', art: 'die', meaning: 'banana', plural: 'Bananen', pType: 'n' }, { word: 'Auto', art: 'das', meaning: 'car', plural: 'Autos', pType: 's' },
  { word: 'Tisch', art: 'der', meaning: 'table', plural: 'Tische', pType: 'e' }, { word: 'Tür', art: 'die', meaning: 'door', plural: 'Türen', pType: 'n' }, { word: 'Haus', art: 'das', meaning: 'house', plural: 'Häuser', pType: 'er' },
  { word: 'Stuhl', art: 'der', meaning: 'chair', plural: 'Stühle', pType: 'e' }, { word: 'Lampe', art: 'die', meaning: 'lamp', plural: 'Lampen', pType: 'n' }, { word: 'Fenster', art: 'das', meaning: 'window', plural: 'Fenster', pType: 'none' },
  { word: 'Hund', art: 'der', meaning: 'dog', plural: 'Hunde', pType: 'e' }, { word: 'Katze', art: 'die', meaning: 'cat', plural: 'Katzen', pType: 'n' }, { word: 'Pferd', art: 'das', meaning: 'horse', plural: 'Pferde', pType: 'e' },
  { word: 'Computer', art: 'der', meaning: 'computer', plural: 'Computer', pType: 'none' }, { word: 'Tastatur', art: 'die', meaning: 'keyboard', plural: 'Tastaturen', pType: 'n' }, { word: 'Handy', art: 'das', meaning: 'mobile phone', plural: 'Handys', pType: 's' },
  { word: 'Löffel', art: 'der', meaning: 'spoon', plural: 'Löffel', pType: 'none' }, { word: 'Gabel', art: 'die', meaning: 'fork', plural: 'Gabeln', pType: 'n' }, { word: 'Messer', art: 'das', meaning: 'knife', plural: 'Messer', pType: 'none' },
  { word: 'Schlüssel', art: 'der', meaning: 'key', plural: 'Schlüssel', pType: 'none' }, { word: 'Tasche', art: 'die', meaning: 'bag', plural: 'Taschen', pType: 'n' }, { word: 'Buch', art: 'das', meaning: 'book', plural: 'Bücher', pType: 'er' },
  { word: 'Baum', art: 'der', meaning: 'tree', plural: 'Bäume', pType: 'e' }, { word: 'Blume', art: 'die', meaning: 'flower', plural: 'Blumen', pType: 'n' }, { word: 'Kind', art: 'das', meaning: 'child', plural: 'Kinder', pType: 'er' },
  { word: 'Mann', art: 'der', meaning: 'man', plural: 'Männer', pType: 'er' }, { word: 'Frau', art: 'die', meaning: 'woman', plural: 'Frauen', pType: 'n' }, { word: 'Mädchen', art: 'das', meaning: 'girl', plural: 'Mädchen', pType: 'none' },
  { word: 'Junge', art: 'der', meaning: 'boy', plural: 'Jungen', pType: 'n' }, { word: 'Schule', art: 'die', meaning: 'school', plural: 'Schulen', pType: 'n' }, { word: 'Brot', art: 'das', meaning: 'bread', plural: 'Brote', pType: 'e' },
  { word: 'Käse', art: 'der', meaning: 'cheese', plural: 'Käse', pType: 'none' }, { word: 'Milch', art: 'die', meaning: 'milk', plural: 'Milch', pType: 'none' }, { word: 'Wasser', art: 'das', meaning: 'water', plural: 'Wasser', pType: 'none' },
  { word: 'Saft', art: 'der', meaning: 'juice', plural: 'Säfte', pType: 'e' }, { word: 'Zeitung', art: 'die', meaning: 'newspaper', plural: 'Zeitungen', pType: 'n' }, { word: 'Bild', art: 'das', meaning: 'picture', plural: 'Bilder', pType: 'er' },
  { word: 'Stift', art: 'der', meaning: 'pen', plural: 'Stifte', pType: 'e' }, { word: 'Schere', art: 'die', meaning: 'scissors', plural: 'Scheren', pType: 'n' }, { word: 'Papier', art: 'das', meaning: 'paper', plural: 'Papiere', pType: 'e' },
  { word: 'Kopf', art: 'der', meaning: 'head', plural: 'Köpfe', pType: 'e' }, { word: 'Hand', art: 'die', meaning: 'hand', plural: 'Hände', pType: 'e' }, { word: 'Bein', art: 'das', meaning: 'leg', plural: 'Beine', pType: 'e' },
  { word: 'Fuß', art: 'der', meaning: 'foot', plural: 'Füße', pType: 'e' }, { word: 'Nase', art: 'die', meaning: 'nose', plural: 'Nasen', pType: 'n' }, { word: 'Auge', art: 'das', meaning: 'eye', plural: 'Augen', pType: 'n' },
  { word: 'Mund', art: 'der', meaning: 'mouth', plural: 'Münder', pType: 'er' }, { word: 'Zunge', art: 'die', meaning: 'tongue', plural: 'Zungen', pType: 'n' }, { word: 'Ohr', art: 'das', meaning: 'ear', plural: 'Ohren', pType: 'n' },
  { word: 'Finger', art: 'der', meaning: 'finger', plural: 'Finger', pType: 'none' }, { word: 'Schulter', art: 'die', meaning: 'shoulder', plural: 'Schultern', pType: 'n' }, { word: 'Herz', art: 'das', meaning: 'heart', plural: 'Herzen', pType: 'n' },
  { word: 'Rücken', art: 'der', meaning: 'back' }, { word: 'Brust', art: 'die', meaning: 'chest' }, { word: 'Blut', art: 'das', meaning: 'blood' },
  { word: 'Hals', art: 'der', meaning: 'neck' }, { word: 'Haut', art: 'die', meaning: 'skin' }, { word: 'Haar', art: 'das', meaning: 'hair' },
  { word: 'Bauch', art: 'der', meaning: 'stomach' }, { word: 'Leber', art: 'die', meaning: 'liver' }, { word: 'Gehirn', art: 'das', meaning: 'brain' },
  { word: 'Knochen', art: 'der', meaning: 'bone' }, { word: 'Muskel', art: 'der', meaning: 'muscle' }, { word: 'Zahn', art: 'der', meaning: 'tooth' },
  { word: 'Arzt', art: 'der', meaning: 'doctor' }, { word: 'Ärztin', art: 'die', meaning: 'female doctor' }, { word: 'Krankenhaus', art: 'das', meaning: 'hospital' },
  { word: 'Patient', art: 'der', meaning: 'patient' }, { word: 'Krankheit', art: 'die', meaning: 'illness' }, { word: 'Medikament', art: 'das', meaning: 'medicine' },
  { word: 'Apotheke', art: 'die', meaning: 'pharmacy' }, { word: 'Rezept', art: 'das', meaning: 'recipe/prescription' }, { word: 'Fieber', art: 'das', meaning: 'fever' },
  { word: 'Schmerz', art: 'der', meaning: 'pain' }, { word: 'Spritze', art: 'die', meaning: 'injection' }, { word: 'Pflaster', art: 'das', meaning: 'plaster' },
  { word: 'Verband', art: 'der', meaning: 'bandage' }, { word: 'Wunde', art: 'die', meaning: 'wound' }, { word: 'Unfall', art: 'der', meaning: 'accident' },
  { word: 'Hilfe', art: 'die', meaning: 'help' }, { word: 'Notfall', art: 'der', meaning: 'emergency' }, { word: 'Polizei', art: 'die', meaning: 'police' },
  { word: 'Feuerwehr', art: 'die', meaning: 'fire department' }, { word: 'Dieb', art: 'der', meaning: 'thief' }, { word: 'Gefängnis', art: 'das', meaning: 'prison' },
  { word: 'Gericht', art: 'das', meaning: 'court' }, { word: 'Anwalt', art: 'der', meaning: 'lawyer' }, { word: 'Gesetz', art: 'das', meaning: 'law' },
  { word: 'Strafe', art: 'die', meaning: 'punishment' }, { word: 'Freiheit', art: 'die', meaning: 'freedom' }, { word: 'Recht', art: 'das', meaning: 'right' },
  { word: 'Staat', art: 'der', meaning: 'state' }, { word: 'Stadt', art: 'die', meaning: 'city' }, { word: 'Land', art: 'das', meaning: 'country' },
  { word: 'Dorf', art: 'das', meaning: 'village' }, { word: 'Straße', art: 'die', meaning: 'street' }, { word: 'Platz', art: 'der', meaning: 'place/square' },
  { word: 'Park', art: 'der', meaning: 'park' }, { word: 'Wald', art: 'der', meaning: 'forest' }, { word: 'Berg', art: 'der', meaning: 'mountain' },
  { word: 'See', art: 'der', meaning: 'lake' }, { word: 'Meer', art: 'das', meaning: 'sea' }, { word: 'Fluss', art: 'der', meaning: 'river' },
  { word: 'Insel', art: 'die', meaning: 'island' }, { word: 'Wüste', art: 'die', meaning: 'desert' }, { word: 'Himmel', art: 'der', meaning: 'sky' },
  { word: 'Sonne', art: 'die', meaning: 'sun' }, { word: 'Mond', art: 'der', meaning: 'moon' }, { word: 'Stern', art: 'der', meaning: 'star' },
  { word: 'Wolke', art: 'die', meaning: 'cloud' }, { word: 'Regen', art: 'der', meaning: 'rain' }, { word: 'Schnee', art: 'der', meaning: 'snow' },
  { word: 'Wind', art: 'der', meaning: 'wind' }, { word: 'Wetter', art: 'das', meaning: 'weather' }, { word: 'Gewitter', art: 'das', meaning: 'thunderstorm' },
  { word: 'Blitz', art: 'der', meaning: 'lightning' }, { word: 'Donner', art: 'der', meaning: 'thunder' }, { word: 'Hitze', art: 'die', meaning: 'heat' },
  { word: 'Kälte', art: 'die', meaning: 'cold' }, { word: 'Eis', art: 'das', meaning: 'ice' }, { word: 'Frühling', art: 'der', meaning: 'spring' },
  { word: 'Sommer', art: 'der', meaning: 'summer' }, { word: 'Herbst', art: 'der', meaning: 'autumn' }, { word: 'Winter', art: 'der', meaning: 'winter' },
  { word: 'Tag', art: 'der', meaning: 'day' }, { word: 'Nacht', art: 'die', meaning: 'night' }, { word: 'Morgen', art: 'der', meaning: 'morning' },
  { word: 'Abend', art: 'der', meaning: 'evening' }, { word: 'Mittag', art: 'der', meaning: 'noon' }, { word: 'Vormittag', art: 'der', meaning: 'morning (before noon)' },
  { word: 'Nachmittag', art: 'der', meaning: 'afternoon' }, { word: 'Woche', art: 'die', meaning: 'week' }, { word: 'Monat', art: 'der', meaning: 'month' },
  { word: 'Jahr', art: 'das', meaning: 'year' }, { word: 'Stunde', art: 'die', meaning: 'hour' }, { word: 'Minute', art: 'die', meaning: 'minute' },
  { word: 'Sekunde', art: 'die', meaning: 'second' }, { word: 'Zeit', art: 'die', meaning: 'time' }, { word: 'Kalender', art: 'der', meaning: 'calendar' },
  { word: 'Uhr', art: 'die', meaning: 'clock/watch' }, { word: 'Wecker', art: 'der', meaning: 'alarm clock' }, { word: 'Termin', art: 'der', meaning: 'appointment' },
  { word: 'Pause', art: 'die', meaning: 'break' }, { word: 'Urlaub', art: 'der', meaning: 'holiday' }, { word: 'Reise', art: 'die', meaning: 'journey' },
  { word: 'Koffer', art: 'der', meaning: 'suitcase' }, { word: 'Pass', art: 'der', meaning: 'passport' }, { word: 'Flugzeug', art: 'das', meaning: 'airplane' },
  { word: 'Zug', art: 'der', meaning: 'train' }, { word: 'Bus', art: 'der', meaning: 'bus' }, { word: 'Fahrrad', art: 'das', meaning: 'bicycle' },
  { word: 'Schiff', art: 'das', meaning: 'ship' }, { word: 'Boot', art: 'das', meaning: 'boat' }, { word: 'Bahnhof', art: 'der', meaning: 'train station' },
  { word: 'Flughafen', art: 'der', meaning: 'airport' }, { word: 'Hafen', art: 'der', meaning: 'harbor' }, { word: 'Hotel', art: 'das', meaning: 'hotel' },
  { word: 'Zimmer', art: 'das', meaning: 'room' }, { word: 'Bett', art: 'das', meaning: 'bed' }, { word: 'Schrank', art: 'der', meaning: 'wardrobe' },
  { word: 'Regal', art: 'das', meaning: 'shelf' }, { word: 'Spiegel', art: 'der', meaning: 'mirror' }, { word: 'Bad', art: 'das', meaning: 'bath' },
  { word: 'Dusche', art: 'die', meaning: 'shower' }, { word: 'Toilette', art: 'die', meaning: 'toilet' }, { word: 'Küche', art: 'die', meaning: 'kitchen' },
  { word: 'Herd', art: 'der', meaning: 'stove' }, { word: 'Kühlschrank', art: 'der', meaning: 'refrigerator' }, { word: 'Topf', art: 'der', meaning: 'pot' },
  { word: 'Pfanne', art: 'die', meaning: 'pan' }, { word: 'Teller', art: 'der', meaning: 'plate' }, { word: 'Glas', art: 'das', meaning: 'glass' },
  { word: 'Tasse', art: 'die', meaning: 'cup' }, { word: 'Flasche', art: 'die', meaning: 'bottle' }, { word: 'Wein', art: 'der', meaning: 'wine' },
  { word: 'Bier', art: 'das', meaning: 'beer' }, { word: 'Kaffee', art: 'der', meaning: 'coffee' }, { word: 'Tee', art: 'der', meaning: 'tea' },
  { word: 'Zucker', art: 'der', meaning: 'sugar' }, { word: 'Salz', art: 'das', meaning: 'salt' }, { word: 'Pfeffer', art: 'der', meaning: 'pepper' },
  { word: 'Öl', art: 'das', meaning: 'oil' }, { word: 'Essig', art: 'der', meaning: 'vinegar' }, { word: 'Fleisch', art: 'das', meaning: 'meat' },
  { word: 'Fisch', art: 'der', meaning: 'fish' }, { word: 'Gemüse', art: 'das', meaning: 'vegetables' }, { word: 'Obst', art: 'das', meaning: 'fruit' },
  { word: 'Kartoffel', art: 'die', meaning: 'potato' }, { word: 'Reis', art: 'der', meaning: 'rice' }, { word: 'Nudel', art: 'die', meaning: 'noodle' },
  { word: 'Suppe', art: 'die', meaning: 'soup' }, { word: 'Salat', art: 'der', meaning: 'salad' }, { word: 'Wurst', art: 'die', meaning: 'sausage' },
  { word: 'Schinken', art: 'der', meaning: 'ham' }, { word: 'Ei', art: 'das', meaning: 'egg' }, { word: 'Butter', art: 'die', meaning: 'butter' },
  { word: 'Honig', art: 'der', meaning: 'honey' }, { word: 'Marmelade', art: 'die', meaning: 'jam' }, { word: 'Kuchen', art: 'der', meaning: 'cake' },
  { word: 'Schokolade', art: 'die', meaning: 'chocolate' }, { word: 'Eiscreme', art: 'die', meaning: 'ice cream' }, { word: 'Getränk', art: 'das', meaning: 'drink' },
  { word: 'Essen', art: 'das', meaning: 'food' }, { word: 'Frühstück', art: 'das', meaning: 'breakfast' }, { word: 'Mittagessen', art: 'das', meaning: 'lunch' },
  { word: 'Abendessen', art: 'das', meaning: 'dinner' }, { word: 'Hunger', art: 'der', meaning: 'hunger' }, { word: 'Durst', art: 'der', meaning: 'thirst' },
  { word: 'Geschmack', art: 'der', meaning: 'taste' }, { word: 'Geruch', art: 'der', meaning: 'smell' }, { word: 'Licht', art: 'das', meaning: 'light' },
  { word: 'Schatten', art: 'der', meaning: 'shadow' }, { word: 'Farbe', art: 'die', meaning: 'color' }, { word: 'Rot', art: 'das', meaning: 'red' },
  { word: 'Blau', art: 'das', meaning: 'blue' }, { word: 'Grün', art: 'das', meaning: 'green' }, { word: 'Gelb', art: 'das', meaning: 'yellow' },
  { word: 'Schwarz', art: 'das', meaning: 'black' }, { word: 'Weiß', art: 'das', meaning: 'white' }, { word: 'Grau', art: 'das', meaning: 'grey' },
  { word: 'Braun', art: 'das', meaning: 'brown' }, { word: 'Rosa', art: 'das', meaning: 'pink' }, { word: 'Lila', art: 'das', meaning: 'purple' },
  { word: 'Orange', art: 'das', meaning: 'orange' }, { word: 'Form', art: 'die', meaning: 'shape' }, { word: 'Kreis', art: 'der', meaning: 'circle' },
  { word: 'Quadrat', art: 'das', meaning: 'square' }, { word: 'Dreieck', art: 'das', meaning: 'triangle' }, { word: 'Linie', art: 'die', meaning: 'line' },
  { word: 'Punkt', art: 'der', meaning: 'dot' }, { word: 'Größe', art: 'die', meaning: 'size' }, { word: 'Länge', art: 'die', meaning: 'length' },
  { word: 'Breite', art: 'die', meaning: 'width' }, { word: 'Höhe', art: 'die', meaning: 'height' }, { word: 'Gewicht', art: 'das', meaning: 'weight' },
  { word: 'Zahl', art: 'die', meaning: 'number' }, { word: 'Eins', art: 'die', meaning: 'one' }, { word: 'Zwei', art: 'die', meaning: 'two' },
  { word: 'Drei', art: 'die', meaning: 'three' }, { word: 'Null', art: 'die', meaning: 'zero' }, { word: 'Summe', art: 'die', meaning: 'sum' },
  { word: 'Teil', art: 'der', meaning: 'part' }, { word: 'Hälfte', art: 'die', meaning: 'half' }, { word: 'Ganzes', art: 'das', meaning: 'whole' },
  { word: 'Menge', art: 'die', meaning: 'amount' }, { word: 'Stück', art: 'das', meaning: 'piece' }, { word: 'Paar', art: 'das', meaning: 'pair' },
  { word: 'Dutzend', art: 'das', meaning: 'dozen' }, { word: 'Kilogramm', art: 'das', meaning: 'kilogram' }, { word: 'Gramm', art: 'das', meaning: 'gram' },
  { word: 'Liter', art: 'der', meaning: 'liter' }, { word: 'Meter', art: 'der', meaning: 'meter' }, { word: 'Zentimeter', art: 'der', meaning: 'centimeter' },
  { word: 'Kilometer', art: 'der', meaning: 'kilometer' }, { word: 'Geld', art: 'das', meaning: 'money' }, { word: 'Preis', art: 'der', meaning: 'price' },
  { word: 'Kosten', art: 'die', meaning: 'costs' }, { word: 'Rechnung', art: 'die', meaning: 'bill/invoice' }, { word: 'Quittung', art: 'die', meaning: 'receipt' },
  { word: 'Bank', art: 'die', meaning: 'bank' }, { word: 'Konto', art: 'das', meaning: 'account' }, { word: 'Karte', art: 'die', meaning: 'card' },
  { word: 'Münze', art: 'die', meaning: 'coin' }, { word: 'Schein', art: 'der', meaning: 'note/bill' }, { word: 'Börse', art: 'die', meaning: 'exchange/purse' },
  { word: 'Einkauf', art: 'der', meaning: 'purchase' }, { word: 'Laden', art: 'der', meaning: 'shop' }, { word: 'Markt', art: 'der', meaning: 'market' },
  { word: 'Supermarkt', art: 'der', meaning: 'supermarket' }, { word: 'Kasse', art: 'die', meaning: 'cash desk' }, { word: 'Kunde', art: 'der', meaning: 'customer' },
  { word: 'Verkäufer', art: 'der', meaning: 'salesman' }, { word: 'Ware', art: 'die', meaning: 'goods' }, { word: 'Angebot', art: 'das', meaning: 'offer' },
  { word: 'Rabatt', art: 'der', meaning: 'discount' }, { word: 'Geschenk', art: 'das', meaning: 'gift' }, { word: 'Arbeit', art: 'die', meaning: 'work' },
  { word: 'Beruf', art: 'der', meaning: 'profession' }, { word: 'Job', art: 'der', meaning: 'job' }, { word: 'Chef', art: 'der', meaning: 'boss' },
  { word: 'Kollege', art: 'der', meaning: 'colleague' }, { word: 'Firma', art: 'die', meaning: 'company' }, { word: 'Büro', art: 'das', meaning: 'office' },
  { word: 'Fabrik', art: 'die', meaning: 'factory' }, { word: 'Werkstatt', art: 'die', meaning: 'workshop' }, { word: 'Lohn', art: 'der', meaning: 'wage' },
  { word: 'Gehalt', art: 'das', meaning: 'salary' }, { word: 'Steuer', art: 'die', meaning: 'tax' }, { word: 'Versicherung', art: 'die', meaning: 'insurance' },
  { word: 'Rente', art: 'die', meaning: 'pension' }, { word: 'Streik', art: 'der', meaning: 'strike' }, { word: 'Erfolg', art: 'der', meaning: 'success' },
  { word: 'Fehler', art: 'der', meaning: 'error' }, { word: 'Plan', art: 'der', meaning: 'plan' }, { word: 'Ziel', art: 'das', meaning: 'goal' },
  { word: 'Aufgabe', art: 'die', meaning: 'task' }, { word: 'Problem', art: 'das', meaning: 'problem' }, { word: 'Lösung', art: 'die', meaning: 'solution' },
  { word: 'Frage', art: 'die', meaning: 'question' }, { word: 'Antwort', art: 'die', meaning: 'answer' }, { word: 'Nachricht', art: 'die', meaning: 'message' },
  { word: 'Information', art: 'die', meaning: 'information' }, { word: 'Wissen', art: 'das', meaning: 'knowledge' }, { word: 'Idee', art: 'die', meaning: 'idea' },
  { word: 'Gedanke', art: 'der', meaning: 'thought' }, { word: 'Meinung', art: 'die', meaning: 'opinion' }, { word: 'Glaube', art: 'der', meaning: 'faith' },
  { word: 'Hoffnung', art: 'die', meaning: 'hope' }, { word: 'Traum', art: 'der', meaning: 'dream' }, { word: 'Angst', art: 'die', meaning: 'fear' },
  { word: 'Liebe', art: 'die', meaning: 'love' }, { word: 'Hass', art: 'der', meaning: 'hate' }, { word: 'Glück', art: 'das', meaning: 'luck/happiness' },
  { word: 'Pech', art: 'das', meaning: 'bad luck' }, { word: 'Freude', art: 'die', meaning: 'joy' }, { word: 'Trauer', art: 'die', meaning: 'grief' },
  { word: 'Wut', art: 'die', meaning: 'anger' }, { word: 'Gefühl', art: 'das', meaning: 'feeling' }, { word: 'Charakter', art: 'der', meaning: 'character' },
  { word: 'Mensch', art: 'der', meaning: 'human' }, { word: 'Person', art: 'die', meaning: 'person' }, { word: 'Leute', art: 'die', meaning: 'people' },
  { word: 'Freund', art: 'der', meaning: 'friend' }, { word: 'Feind', art: 'der', meaning: 'enemy' }, { word: 'Nachbar', art: 'der', meaning: 'neighbor' },
  { word: 'Gast', art: 'der', meaning: 'guest' }, { word: 'Familie', art: 'die', meaning: 'family' }, { word: 'Eltern', art: 'die', meaning: 'parents' },
  { word: 'Vater', art: 'der', meaning: 'father' }, { word: 'Mutter', art: 'die', meaning: 'mother' }, { word: 'Sohn', art: 'der', meaning: 'son' },
  { word: 'Tochter', art: 'die', meaning: 'daughter' }, { word: 'Bruder', art: 'der', meaning: 'brother' }, { word: 'Schwester', art: 'die', meaning: 'sister' },
  { word: 'Opa', art: 'der', meaning: 'grandpa' }, { word: 'Oma', art: 'die', meaning: 'grandma' }, { word: 'Onkel', art: 'der', meaning: 'uncle' },
  { word: 'Tante', art: 'die', meaning: 'aunt' }, { word: 'Cousin', art: 'der', meaning: 'male cousin' }, { word: 'Cousine', art: 'die', meaning: 'female cousin' },
  { word: 'Neffe', art: 'der', meaning: 'nephew' }, { word: 'Nichte', art: 'die', meaning: 'niece' }, { word: 'Baby', art: 'das', meaning: 'baby' },
  { word: 'Hochzeit', art: 'die', meaning: 'wedding' }, { word: 'Geburtstag', art: 'der', meaning: 'birthday' }, { word: 'Fest', art: 'das', meaning: 'festival' },
  { word: 'Party', art: 'die', meaning: 'party' }, { word: 'Besuch', art: 'der', meaning: 'visit' }, { word: 'Gespräch', art: 'das', meaning: 'conversation' },
  { word: 'Wort', art: 'das', meaning: 'word' }, { word: 'Satz', art: 'der', meaning: 'sentence' }, { word: 'Text', art: 'der', meaning: 'text' },
  { word: 'Sprache', art: 'die', meaning: 'language' }, { word: 'Stimme', art: 'die', meaning: 'voice' }, { word: 'Lied', art: 'das', meaning: 'song' },
  { word: 'Musik', art: 'die', meaning: 'music' }, { word: 'Radio', art: 'das', meaning: 'radio' }, { word: 'Fernsehen', art: 'das', meaning: 'television' },
  { word: 'Film', art: 'der', meaning: 'film' }, { word: 'Kino', art: 'das', meaning: 'cinema' }, { word: 'Theater', art: 'das', meaning: 'theater' },
  { word: 'Museum', art: 'das', meaning: 'museum' }, { word: 'Konzert', art: 'das', meaning: 'concert' }, { word: 'Spiel', art: 'das', meaning: 'game' },
  { word: 'Sport', art: 'der', meaning: 'sport' }, { word: 'Fußball', art: 'der', meaning: 'football' }, { word: 'Tennis', art: 'das', meaning: 'tennis' },
  { word: 'Schwimmen', art: 'das', meaning: 'swimming' }, { word: 'Laufen', art: 'das', meaning: 'running' }, { word: 'Training', art: 'das', meaning: 'training' },
  { word: 'Mannschaft', art: 'die', meaning: 'team' }, { word: 'Sieg', art: 'der', meaning: 'victory' }, { word: 'Niederlage', art: 'die', meaning: 'defeat' },
  { word: 'Rekord', art: 'der', meaning: 'record' }, { word: 'Hobby', art: 'das', meaning: 'hobby' }, { word: 'Freizeit', art: 'die', meaning: 'leisure' },
  { word: 'Natur', art: 'die', meaning: 'nature' }, { word: 'Umwelt', art: 'die', meaning: 'environment' }, { word: 'Tier', art: 'das', meaning: 'animal' },
  { word: 'Vogel', art: 'der', meaning: 'bird' }, { word: 'Fisch', art: 'der', meaning: 'fish' }, { word: 'Insekt', art: 'das', meaning: 'insect' },
  { word: 'Pflanze', art: 'die', meaning: 'plant' }, { word: 'Gras', art: 'das', meaning: 'grass' }, { word: 'Blatt', art: 'das', meaning: 'leaf' },
  { word: 'Wurzel', art: 'die', meaning: 'root' }, { word: 'Samen', art: 'der', meaning: 'seed' }, { word: 'Erde', art: 'die', meaning: 'earth' },
  { word: 'Stein', art: 'der', meaning: 'stone' }, { word: 'Sand', art: 'der', meaning: 'sand' }, { word: 'Staub', art: 'der', meaning: 'dust' },
  { word: 'Müll', art: 'der', meaning: 'rubbish' }, { word: 'Luft', art: 'die', meaning: 'air' }, { word: 'Feuer', art: 'das', meaning: 'fire' },
  { word: 'Rauch', art: 'der', meaning: 'smoke' }, { word: 'Asche', art: 'die', meaning: 'ash' }, { word: 'Wärme', art: 'die', meaning: 'warmth' },
  { word: 'Energie', art: 'die', meaning: 'energy' }, { word: 'Kraft', art: 'die', meaning: 'power/force' }, { word: 'Macht', art: 'die', meaning: 'power/might' },
  { word: 'Gewalt', art: 'die', meaning: 'violence' }, { word: 'Krieg', art: 'der', meaning: 'war' }, { word: 'Frieden', art: 'der', meaning: 'peace' },
  { word: 'Sicherheit', art: 'die', meaning: 'security' }, { word: 'Gefahr', art: 'die', meaning: 'danger' }, { word: 'Schutz', art: 'der', meaning: 'protection' },
  { word: 'Ordnung', art: 'die', meaning: 'order' }, { word: 'Chaos', art: 'das', meaning: 'chaos' }, { word: 'System', art: 'das', meaning: 'system' },
  { word: 'Struktur', art: 'die', meaning: 'structure' }, { word: 'Funktion', art: 'die', meaning: 'function' }, { word: 'Wirkung', art: 'die', meaning: 'effect' },
  { word: 'Ursache', art: 'die', meaning: 'cause' }, { word: 'Grund', art: 'der', meaning: 'reason' }, { word: 'Beweis', art: 'der', meaning: 'proof' },
  { word: 'Tatsache', art: 'die', meaning: 'fact' }, { word: 'Wahrheit', art: 'die', meaning: 'truth' }, { word: 'Lüge', art: 'die', meaning: 'lie' },
  { word: 'Geheimnis', art: 'das', meaning: 'secret' }, { word: 'Rätsel', art: 'das', meaning: 'riddle' }, { word: 'Zeichen', art: 'das', meaning: 'sign' },
  { word: 'Symbol', art: 'das', meaning: 'symbol' }, { word: 'Bildschirm', art: 'der', meaning: 'screen' }, { word: 'Maus', art: 'die', meaning: 'mouse' },
  { word: 'Drucker', art: 'der', meaning: 'printer' }, { word: 'Internet', art: 'das', meaning: 'internet' }, { word: 'Website', art: 'die', meaning: 'website' },
  { word: 'E-Mail', art: 'die', meaning: 'e-mail' }, { word: 'Passwort', art: 'das', meaning: 'password' }, { word: 'Datei', art: 'die', meaning: 'file' },
  { word: 'Ordner', art: 'der', meaning: 'folder' }, { word: 'Programm', art: 'das', meaning: 'program' }, { word: 'Software', art: 'die', meaning: 'software' },
  { word: 'Hardware', art: 'die', meaning: 'hardware' }, { word: 'Netzwerk', art: 'das', meaning: 'network' }, { word: 'Server', art: 'der', meaning: 'server' },
  { word: 'Daten', art: 'die', meaning: 'data' }, { word: 'Kamera', art: 'die', meaning: 'camera' }, { word: 'Foto', art: 'das', meaning: 'photo' },
  { word: 'Video', art: 'das', meaning: 'video' }, { word: 'Mikrofon', art: 'das', meaning: 'microphone' }, { word: 'Lautsprecher', art: 'der', meaning: 'speaker' },
  { word: 'Kopfhörer', art: 'der', meaning: 'headphones' }, { word: 'Kabel', art: 'das', meaning: 'cable' }, { word: 'Batterie', art: 'die', meaning: 'battery' },
  { word: 'Strom', art: 'der', meaning: 'electricity' }, { word: 'Steckdose', art: 'die', meaning: 'socket' }, { word: 'Schalter', art: 'der', meaning: 'switch' },
  { word: 'Maschine', art: 'die', meaning: 'machine' }, { word: 'Motor', art: 'der', meaning: 'motor' }, { word: 'Werkzeug', art: 'das', meaning: 'tool' },
  { word: 'Hammer', art: 'der', meaning: 'hammer' }, { word: 'Nagel', art: 'der', meaning: 'nail' }, { word: 'Schraube', art: 'die', meaning: 'screw' },
  { word: 'Säge', art: 'die', meaning: 'saw' }, { word: 'Zange', art: 'die', meaning: 'pliers' }, { word: 'Leiter', art: 'die', meaning: 'ladder' },
  { word: 'Farbe', art: 'die', meaning: 'color' }, { word: 'Pinsel', art: 'der', meaning: 'brush' }, { word: 'Kleber', art: 'der', meaning: 'glue' },
  { word: 'Band', art: 'das', meaning: 'tape' }, { word: 'Faden', art: 'der', meaning: 'thread' }, { word: 'Nadel', art: 'die', meaning: 'needle' },
  { word: 'Stoff', art: 'der', meaning: 'fabric' }, { word: 'Wolle', art: 'die', meaning: 'wool' }, { word: 'Leder', art: 'das', meaning: 'leather' },
  { word: 'Holz', art: 'das', meaning: 'wood' }, { word: 'Metall', art: 'das', meaning: 'metal' }, { word: 'Eisen', art: 'das', meaning: 'iron' },
  { word: 'Gold', art: 'das', meaning: 'gold' }, { word: 'Silber', art: 'das', meaning: 'silver' }, { word: 'Glas', art: 'das', meaning: 'glass' },
  { word: 'Plastik', art: 'das', meaning: 'plastic' }, { word: 'Gummi', art: 'das', meaning: 'rubber' }, { word: 'Papier', art: 'das', meaning: 'paper' },
  { word: 'Karton', art: 'der', meaning: 'cardboard' }, { word: 'Box', art: 'die', meaning: 'box' }, { word: 'Behälter', art: 'der', meaning: 'container' },
  { word: 'Sack', art: 'der', meaning: 'sack' }, { word: 'Tüte', art: 'die', meaning: 'bag' }, { word: 'Eimer', art: 'der', meaning: 'bucket' },
  { word: 'Korb', art: 'der', meaning: 'basket' }, { word: 'Netz', art: 'das', meaning: 'net' }, { word: 'Kette', art: 'die', meaning: 'chain' },
  { word: 'Ring', art: 'der', meaning: 'ring' }, { word: 'Schmuck', art: 'der', meaning: 'jewelry' }, { word: 'Uhr', art: 'die', meaning: 'watch' },
  { word: 'Brille', art: 'die', meaning: 'glasses' }, { word: 'Regenschirm', art: 'der', meaning: 'umbrella' }, { word: 'Kleidung', art: 'die', meaning: 'clothing' },
  { word: 'Hose', art: 'die', meaning: 'trousers' }, { word: 'Hemd', art: 'das', meaning: 'shirt' }, { word: 'T-Shirt', art: 'das', meaning: 't-shirt' },
  { word: 'Jacke', art: 'die', meaning: 'jacket' }, { word: 'Mantel', art: 'der', meaning: 'coat' }, { word: 'Kleid', art: 'das', meaning: 'dress' },
  { word: 'Rock', art: 'der', meaning: 'skirt' }, { word: 'Pullover', art: 'der', meaning: 'sweater' }, { word: 'Schuh', art: 'der', meaning: 'shoe' },
  { word: 'Socke', art: 'die', meaning: 'sock' }, { word: 'Mütze', art: 'die', meaning: 'cap' }, { word: 'Hut', art: 'der', meaning: 'hat' },
  { word: 'Handschuh', art: 'der', meaning: 'glove' }, { word: 'Gürtel', art: 'der', meaning: 'belt' }, { word: 'Knopf', art: 'der', meaning: 'button' },
  { word: 'Reißverschluss', art: 'der', meaning: 'zipper' }, { word: 'Tasche', art: 'die', meaning: 'pocket/bag' }, { word: 'Rucksack', art: 'der', meaning: 'backpack' },
  { word: 'Koffer', art: 'der', meaning: 'suitcase' }, { word: 'Brieftasche', art: 'die', meaning: 'wallet' }, { word: 'Brille', art: 'die', meaning: 'glasses' },
  { word: 'Sonnenbrille', art: 'die', meaning: 'sunglasses' }, { word: 'Uhr', art: 'die', meaning: 'clock' }, { word: 'Armband', art: 'das', meaning: 'bracelet' },
  { word: 'Halskette', art: 'die', meaning: 'necklace' }, { word: 'Ohrring', art: 'der', meaning: 'earring' }, { word: 'Parfüm', art: 'das', meaning: 'perfume' },
  { word: 'Seife', art: 'die', meaning: 'soap' }, { word: 'Shampoo', art: 'das', meaning: 'shampoo' }, { word: 'Zahnpasta', art: 'die', meaning: 'toothpaste' },
  { word: 'Zahnbürste', art: 'die', meaning: 'toothbrush' }, { word: 'Handtuch', art: 'das', meaning: 'towel' }, { word: 'Bürste', art: 'die', meaning: 'brush' },
  { word: 'Kamm', art: 'der', meaning: 'comb' }, { word: 'Rasierer', art: 'der', meaning: 'razor' }, { word: 'Schminke', art: 'die', meaning: 'makeup' },
  { word: 'Lippenstift', art: 'der', meaning: 'lipstick' }, { word: 'Nagellack', art: 'der', meaning: 'nail polish' }, { word: 'Spiegel', art: 'der', meaning: 'mirror' },
  { word: 'Föhn', art: 'der', meaning: 'hairdryer' }, { word: 'Waage', art: 'die', meaning: 'scales' }, { word: 'Thermometer', art: 'das', meaning: 'thermometer' }
];
